#![deny(unreachable_pub)]

pub mod agent;
pub mod checks;
pub mod compaction;
pub mod diagnostics;
pub mod eval;
pub mod events;
pub mod gate;
pub mod hooks;
pub mod instructions;
pub mod mcp;
pub mod operator_queue;
pub mod packs;
pub mod planner;
pub mod project_guidance;
pub mod providers;
pub mod repo_map;
pub mod repro;
pub mod scaffold;
pub mod session;
pub mod store;
pub mod taint;
pub mod target;
pub mod taskgraph;
pub mod tools;
pub mod trust;
pub mod tui;
pub mod types;
